export const successMessage = {
     SucessfullyUserCreated: "User Created Successfully",
     SuccessfullyUserUpdated: "User Updated Successfully",
     SuccessfullyUserDeleted: "User Deleted Successfully",
     SuccessfullyUserLoggedIn: "User Logged in Successfully",
     SuccessfullySignedUp: "User Signed Up Successfully",
     SuccessfullyLoggedOut: "USer Logged Out Successfully",
     SucessfullyBookCreated: "Book Created Succesfully",
     SuccessfullyBookUpdated: "Book Updated Sucessfully",
     SuccessfullyBookDeleted: "Book deleted Succesfully",
     SuccessfullyAuthorCreated: "Author created successfully",
     SuccessfullyAuthorUpdated: "Author updated successfully",
     SuccessfullyAuthorDeleted: "Author deleted successfully",
     SuccessfullyCategoryCreated: "Category created successfully",
     SuccessfullyCategoryDeleted: "Category deleted successfully",
     SuccessfullyCategoryUpdated: "Category updated sucessfully",
};
export const errorMessage = {
     InternalServerError: "Internal Server Error!!",
     ErrorInUserCreating: "Error in creating user",
     ErrorInGettingUser: "Error in getting User",
     ErrorInDeletingUser: "Error in deleting User",
     ErrorInUpdatingUser: "Error in Updating User",
     ErrorInCreatingBook: "Error in creating Book",
     ErrorInGettingBook: "Error in getting Book",
     ErrorInUpdatingBook: "Error in Updating Book",
     ErrorInDeletingBook: "Error in Deleting Book",
     ErrorInCreatingAuthor: "Error in Creating Author",
     ErrorInGettingAuthor: "Error in Getting Author",
     ErrorInUpdatingAuthor: "Error in Updating Author",
     ErrorInDeletingAuthor: "Error in Deleting Author",
     ErrorInCreatingCategory: "Error in creating Book",
     ErrorInGettingCategory: "Error in getting Category",
     ErrorInUpdatingCategory: "Error in updating Category",
     ErrorInDeletingCategory: "Error in Deleting Category",
     ErrorInUserLoggedIn: "Error In User Logging",
     ErrorInUSerSignedUP: "Error In User Signing up",
     ErrorInUserLoggedOut: "Error In UserLogging Out",
     UserIsNotLoggedIn: "User is not Logged in",
     InvalidToken: "Invalid Token",
};

export const FatalErrorMessage = {
     UserNotFound: "User Not Found",
     BookNotFound: "Book Not Found",
     CategoryNotFound: "Category Not Found",
     AuthorNotFound: "Author Not Found",
     InvalidCredentials: "Invalid Credentials",
     UnauthorizedAction: "UnauthorizedAction",
     DataNotFound: "Data NOt Found",
     AlreadyExitsUser:"User Already Exists"
};
